language: php

services: mysql

php:
  - 7.3

env:
  - APPLICATION_ENV="testing" DB="mysql" DB_USERNAME="root"

before_install:
  - mysql -u$DB_USERNAME -e 'create database tests;'
  - unzip tests/sakila.zip
  - mysql -u$DB_USERNAME tests < sakila.sql

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - mkdir -p tmp/logs
  - mkdir -p build/logs
  - php vendor/bin/phpunit --configuration tests/$DB.xml

after_script:
  - php vendor/bin/coveralls -v
